Parameters:

  ApplicationName:
    Type: String
    Default: helloworld-codedeploy-application
  CodeDeployRoleName:
    Type: String
    Default: helloworld-codedeploy-role
  DeploymentGroupName:
    Type: String
    Default: helloworld-dev
  EnvironmentTag:
    Type: String
    Default: Dev
  ApplicationTag:
    Type: String
    Default: helloworld

Resources:

  CodeDeployRole:
    Type: AWS::IAM::Role
    Properties: 
      RoleName: !Ref CodeDeployRoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codedeploy.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSCodeDeployRole"
        - "arn:aws:iam::aws:policy/AWSCodeDeployRoleForECS"

  HelloworldApplication:
    Type: AWS::CodeDeploy::Application
    Properties:
      ApplicationName: !Ref ApplicationName 
      ComputePlatform: Server

  DeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    DependsOn : HelloworldApplication
    Properties:
      ApplicationName: !Ref ApplicationName
      DeploymentGroupName: !Ref DeploymentGroupName
      ServiceRoleArn: !GetAtt CodeDeployRole.Arn
      Ec2TagFilters:
        - Key: Environment
          Value: !Ref EnvironmentTag
          Type: KEY_AND_VALUE
        - Key: Application
          Value: !Ref ApplicationTag
          Type: KEY_AND_VALUE